// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXDOtnoCAMB2mM01FkBMy_rtHHIcaf7s',
    appId: '1:385219554936:web:75159b61dcef2b0071c78d',
    messagingSenderId: '385219554936',
    projectId: 'paramotor-91471',
    authDomain: 'paramotor-91471.firebaseapp.com',
    databaseURL: 'https://paramotor-91471-default-rtdb.firebaseio.com',
    storageBucket: 'paramotor-91471.appspot.com',
    measurementId: 'G-6376TVJ2G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HHGlI7PYNM_i0PodQXfUflwYVrDKAyM',
    appId: '1:385219554936:android:9bc5433c92798e5e71c78d',
    messagingSenderId: '385219554936',
    projectId: 'paramotor-91471',
    databaseURL: 'https://paramotor-91471-default-rtdb.firebaseio.com',
    storageBucket: 'paramotor-91471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSb7Dx1lLuVteLXeHFKysf5yEze5JU2wE',
    appId: '1:385219554936:ios:8071fdebe1cdbace71c78d',
    messagingSenderId: '385219554936',
    projectId: 'paramotor-91471',
    databaseURL: 'https://paramotor-91471-default-rtdb.firebaseio.com',
    storageBucket: 'paramotor-91471.appspot.com',
    iosClientId: '385219554936-cq38nqq872qsjg1gg8gdeqrmpufivjph.apps.googleusercontent.com',
    iosBundleId: 'com.example.paramotor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSb7Dx1lLuVteLXeHFKysf5yEze5JU2wE',
    appId: '1:385219554936:ios:8071fdebe1cdbace71c78d',
    messagingSenderId: '385219554936',
    projectId: 'paramotor-91471',
    databaseURL: 'https://paramotor-91471-default-rtdb.firebaseio.com',
    storageBucket: 'paramotor-91471.appspot.com',
    iosClientId: '385219554936-cq38nqq872qsjg1gg8gdeqrmpufivjph.apps.googleusercontent.com',
    iosBundleId: 'com.example.paramotor',
  );
}
